spring:
  application:
    name: mercado-livro
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: 7a0bf29f1c8e1248ae3966d45551fe99cf13140bf29f1c8e1248ae3966d45551fe99cf13
  expiration: 100000